name = "sckkweb"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-04-02"
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"
build.command = "bun run build"

[observability.logs]
enabled = true
